// Generated by CoffeeScript 1.10.0
var CookieJar, address, async, cookies, fetchStream, fetchUrl, fetchpage, getheaders, hddInfo, oldcookies, postheaders, ref, ref1, ref2, servicePwd, trdpwd, trdpwdEns, url, userName, util, vcode;

util = require('util');

async = require('async');

vcode = require('./getvcode');

hddInfo = require('./hddInfo');

address = require('./getaddress');

ref = require('./.mainaccount'), userName = ref.userName, trdpwd = ref.trdpwd, trdpwdEns = ref.trdpwdEns, servicePwd = ref.servicePwd;

ref1 = require('../refs/experiments/options'), postheaders = ref1.postheaders, getheaders = ref1.getheaders;

ref2 = require('fetch'), fetchUrl = ref2.fetchUrl, fetchStream = ref2.fetchStream, CookieJar = ref2.CookieJar;

delete postheaders.cookies;

cookies = new CookieJar();

oldcookies = cookies;

url = 'https://service.htsc.com.cn/service/login.jsp';

fetchpage = function(callback) {
  return fetchUrl(url, {
    headers: getheaders,
    method: 'GET',
    cookieJar: cookies
  }, function(err, meta, body) {
    return callback(err, meta, body);
  });
};

fetchpage(function(err, meta, body) {
  return console.log(meta);
});

//# sourceMappingURL=fetchlogin1.js.map
