// Generated by CoffeeScript 1.10.0

/* 驗證碼
 */
var ocr, url, vcode;

ocr = require('ocr-by-image-url');

url = "https://service.htsc.com.cn/service/pic/verifyCodeImage.jsp?ran=" + (Math.random());

vcode = function(viurl, callback) {
  return ocr.getImageText(viurl, function(err, text) {
    var code;
    if (err) {
      return vcode(viurl, callback);
    }
    code = text.trim();
    if (!/^\w{4}$/.test(code)) {
      return vcode(viurl, callback);
    }
    return callback(null, code);
  });
};

module.exports = vcode;


/* tested
vcode url, (err, code)->
  console.log code unless err?
 */

//# sourceMappingURL=getvcode.js.map
