// Generated by CoffeeScript 1.10.0
var CookieJar, address, async, cookies, fetchStream, fetchUrl, fetchpage, getheaders, getpage, hddInfo, needle, obj, oldcookies, options, postheaders, ref, ref1, ref2, servicePwd, trdpwd, trdpwdEns, url, userName, util, vcode, vcurl;

util = require('util');

async = require('async');

vcode = require('./getvcode');

hddInfo = require('./hddInfo');

address = require('./getaddress');

ref = require('./.mainaccount'), userName = ref.userName, trdpwd = ref.trdpwd, trdpwdEns = ref.trdpwdEns, servicePwd = ref.servicePwd;

ref1 = require('../refs/experiments/options'), postheaders = ref1.postheaders, getheaders = ref1.getheaders;

needle = require('needle');

ref2 = require('fetch'), fetchUrl = ref2.fetchUrl, fetchStream = ref2.fetchStream, CookieJar = ref2.CookieJar;

delete postheaders.cookies;

cookies = new CookieJar();

cookies.setCookie(getheaders.cookies);

oldcookies = cookies;

options = {
  headers: getheaders,
  method: 'GET',
  cookieJar: cookies
};

url = 'https://service.htsc.com.cn/service/login.jsp';

fetchpage = function(callback) {
  return fetchUrl(url, options, function(err, meta, body) {
    if (err != null) {
      console.error(err);
    } else {
      return callback(err, meta.cookieJar.cookies);
    }
  });
};

fetchpage(function(err, meta) {
  return console.log("ok");
});

url = 'https://service.htsc.com.cn/service/login.jsp';

options = {
  headers: getheaders,
  method: 'GET',
  cookies: cookies.cookies,
  parse_cookies: true,
  follow_set_cookies: true
};

getpage = function(callback) {
  return needle.get(url, options, function(err, resp, body) {
    if (err != null) {
      return callback(err);
    } else {
      return callback(err, resp);
    }
  });
};

vcurl = "https://service.htsc.com.cn/service/pic/verifyCodeImage.jsp?ran=" + (Math.random());

obj = {
  fet: function(callback) {
    return setTimeout((function() {
      return fetchpage(callback);
    }), 400);
  },
  req: function(callback) {
    return setTimeout((function() {
      return getpage(callback);
    }), 400);
  },
  vcode: function(callback) {
    return setTimeout((function() {
      return vcode(vcurl, callback);
    }), 400);
  },
  ipmac: function(callback) {
    return setTimeout((function() {
      return address(callback);
    }), 400);
  }
};

async.parallel(obj, function(err, results) {
  var backup, callback, ip, mac, p1, p2, p3, p4, p5, payload, ref3;
  (ref3 = results.ipmac, ip = ref3.ip, mac = ref3.mac), vcode = results.vcode;
  cookies = cookies.cookies;
  postheaders.cookies = cookies;
  console.log(vcode.trim(), cookies);
  url = 'https://service.htsc.com.cn/service/loginAction.do?method=login';
  options = {
    method: "POST",
    url: url,
    headers: postheaders,
    cookies: cookies,
    parse_cookies: true,
    follow_set_cookies: true
  };
  p1 = "userType=jy&loginEvent=1&trdpwdEns=2d8c0c21d479305c539e7a49ecd87d4d&";
  p2 = "macaddr=60:33:4B:09:BF:0F&hddInfo=" + hddInfo + "&lipInfo=" + ip + "&";
  p3 = "CPU=QkZFQkZCRkYwMDAzMDY2MQ%3D%3D&PCN=U0RXTS0yMDEzMDkxNFNX&PI=QyxOVEZTLDYwLjAwMzg%3D&";
  p4 = "topath=null&accountType=1&userName=080300007199&";
  p5 = "servicePwd=19660522&trdpwd=2d8c0c21d479305c539e7a49ecd87d4d&vcode=" + (vcode.trim());
  payload = "" + p1 + p2 + p4 + p5;
  backup = {
    loginEvent: 1,
    topath: null,
    accountType: 1,
    userType: 'jy',
    userName: userName,
    trdpwd: trdpwd,
    trdpwdEns: trdpwdEns,
    servicePwd: servicePwd,
    macaddr: '60:33:4B:09:BF:0F',
    lipInfo: "" + ip,
    vcode: "" + (vcode.trim()),
    hddInfo: "" + hddInfo
  };
  callback = function(err, resp, body) {
    if (err) {
      return console.error(err);
    } else {
      if ((body.indexOf('欢迎')) < 0) {
        return console.error(resp.cookies, body, '登錄不成功');
      } else {
        return console.log(resp.cookies, body);
      }
    }
  };
  return needle.post(url, options, payload, callback);
});


/*  採用fetch模塊,實現登錄的理論過程:
    get 'https://service.htsc.com.cn/service/pic/verifyCodeImage.jsp?ran=' 獲取驗證碼
    get 'https://service.htsc.com.cn/service/login.jsp' 以便取得並記住cookies
    post  'https://service.htsc.com.cn/service/loginAction.do?method=login' 登錄
 */

//# sourceMappingURL=needlelogin.js.map
